// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvcDzl8-Q74x2NNZX2jL5BJheZZ-NBOZE',
    appId: '1:548175123674:web:5d252a4aa41402a3bd41e3',
    messagingSenderId: '548175123674',
    projectId: 'mirza-mahmud---portfolio',
    authDomain: 'mirza-mahmud---portfolio.firebaseapp.com',
    storageBucket: 'mirza-mahmud---portfolio.firebasestorage.app',
    measurementId: 'G-VWKKB3TJ0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgeYFwE3EjfLK-87E-qmu_-ng8-S0wB4',
    appId: '1:548175123674:android:b9e55dca778aea9abd41e3',
    messagingSenderId: '548175123674',
    projectId: 'mirza-mahmud---portfolio',
    storageBucket: 'mirza-mahmud---portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo4EbpZay6xAJvIuCBr2p3Hkj1vV1i5m0',
    appId: '1:548175123674:ios:8d9ca92e3727307cbd41e3',
    messagingSenderId: '548175123674',
    projectId: 'mirza-mahmud---portfolio',
    storageBucket: 'mirza-mahmud---portfolio.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWebsite',
  );
}
